apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: env-api-backend
spec:
  backendType: secretsManager
  dataFrom:
  - arn:aws:secretsmanager:eu-west-2:439304389429:secret:{{ cookiecutter.slug }}/staging/app/env-api-backend-6mQoVP
