apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ cookiecutter.slug }}-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/hostname: staging.{{ cookiecutter.host }}
    external-dns.alpha.kubernetes.io/managed: 'true'
    # ingress.kubernetes.io/force-ssl-redirect: 'true'
    # kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp

spec:
  rules:
  - host: staging.{{ cookiecutter.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ cookiecutter.slug }}-svc
            port:
              name: web