## hey -c 5 -m GET -H "Authorization: Token 3d3cc177af948156bcdffe2b78f0adb72b51620e" https://api.stepoutoftheriver.com/api/v1/meditations/1/
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ cookiecutter.slug }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ cookiecutter.slug }}
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: 600Mi
