apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ cookiecutter.slug }}-production-ing
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ cookiecutter.host }}
    external-dns.alpha.kubernetes.io/managed: 'true'
    # ingress.kubernetes.io/force-ssl-redirect: 'true'
    # kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    - api.{{ cookiecutter.host }}
    secretName: {{ cookiecutter.slug }}-cert # < cert-manager will store the created certificate in this secret.
  rules:
  - host: api.{{ cookiecutter.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ cookiecutter.slug }}-svc
            port:
              name: web
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: {{ cookiecutter.slug }}-auth-svc
            port:
              name: web
      - path: /accounts
        pathType: Prefix
        backend:
          service:
            name: {{ cookiecutter.slug }}-auth-svc
            port:
              name: web
      - path: /password/reset
        pathType: Prefix
        backend:
          service:
            name: {{ cookiecutter.slug }}-auth-svc
            port:
              name: web
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: {{ cookiecutter.slug }}-svc
            port:
              name: static
