apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- svc.yaml


configMapGenerator:
- name: caddy-file-cm
  files:
  - Caddyfile=Caddyfile
- name: {{ cookiecutter.slug }}-app-config
  literals:
  - SITE_ID=1
